# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 466d97f30d50414c32c570fe77501988bed9c69b91b2d3f8caffd20b34d55b084c18f54c7111407f3deb304db8bac78d490518e9e52953b525de221431da11d8

test:
  secret_key_base: 1c902c8a8656d84e4cd0ba81e4f425a8c5323968a343bbd95d2a0b5472866da9453ab745ecfd8d3770bc7e7e820362d1b3ebf447f449fee4286357410c143445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
